# Generated by Django 2.1.5 on 2019-01-30 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190130_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='specialVehicleInfo',
            new_name='special_vehicle_info',
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='vehicleNumber',
            new_name='vehicle_number',
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
