# Generated by Django 2.1.5 on 2019-01-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190130_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_plate_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='maximum_passengers',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
