# Generated by Django 2.1.5 on 2019-01-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_driverprofile_is_busy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='is_busy',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='real_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
