# Generated by Django 2.1.5 on 2019-01-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190131_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license_plate_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='maximum_passengers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='real_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
