# Generated by Django 2.1.5 on 2019-02-01 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190131_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driverProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
