# Generated by Django 2.1.5 on 2019-01-31 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=1023)),
                ('required_arrival_time', models.DateTimeField()),
                ('number_of_passengers', models.IntegerField()),
                ('requested_vehicle_type', models.CharField(blank=True, max_length=255)),
                ('special_reqeust', models.TextField(blank=True)),
                ('ride_status', models.CharField(default='open', max_length=255)),
                ('can_be_shared', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('ride_sharers', models.ManyToManyField(related_name='ride_sharers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
