# Generated by Django 2.1.5 on 2019-01-31 20:47

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='number_of_passengers',
            new_name='passenger_number_from_onwer',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_sharers',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='sharer_id_and_passenger_number_pair',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='sharers',
            field=models.ManyToManyField(related_name='sharers', to=settings.AUTH_USER_MODEL),
        ),
    ]
