# Generated by Django 2.1.5 on 2019-02-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_auto_20190201_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='passenger_number_from_onwer',
            new_name='passenger_number_from_owner',
        ),
    ]
