# Generated by Django 2.1.5 on 2019-02-01 20:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20190201_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharer_id_and_passenger_number_pair',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
