# Generated by Django 2.1.5 on 2019-02-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_auto_20190201_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passenger_number_in_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
