# Generated by Django 2.1.5 on 2019-02-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_ride_passenger_number_in_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='special_reqeust',
            new_name='special_request',
        ),
    ]
