# Generated by Django 2.1.5 on 2019-02-04 02:07

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_auto_20190202_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharer_id_and_passenger_number_pair',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='sharers',
            field=models.ManyToManyField(blank=True, null=True, related_name='rides_as_sharer', to=settings.AUTH_USER_MODEL),
        ),
    ]
