# Generated by Django 2.1.5 on 2019-02-04 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_auto_20190204_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharers',
            field=models.ManyToManyField(blank=True, related_name='rides_as_sharer', to=settings.AUTH_USER_MODEL),
        ),
    ]
